export const PROJECT_REQUEST = 'PROJECT_REQUEST';
export const PROJECT_REQUEST_SUCCESS = 'PROJECT_REQUEST_SUCCESS';
export const PROJECT_REQUEST_FAIL = 'PROJECT_REQUEST_FAIL';

export const PROJECT_SUBMIT_REQUEST = 'PROJECT_SUBMIT_REQUEST';
export const PROJECT_SUBMIT_SUCCESS = 'PROJECT_SUBMIT_SUCCESS';
export const PROJECT_SUBMIT_FAIL = 'PROJECT_SUBMIT_FAIL';